config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :warehouses
  resources :suppliers, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :address, :city, :state, :postal_code, :email,
            :phone_number, presence: true
  validates :registration_number, :email, :phone_number, uniqueness: true
  validates :registration_number, format: { with: /\A\d{14}\z/ }
  validates :state, format: { with: /\A[A-Z]{2}\z/ }
  validates :postal_code, format: { with: /\A\d{5}-\d{3}\z/ }
  validates :phone_number, format: { with: /\d{10}\z/ }
  validates :registration_number, length: { is: 14 }
  validates :state, length: { is: 2 }
  validates :postal_code, length: { is: 9 }
  validates :phone_number, length: { in: 10..11 }
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :area, :address, :postal_code, :description, presence: true
  validates :name, :code, uniqueness: true
  validates :code, format: { with: /\A[A-Z]{3}\z/ }
  validates :postal_code, format: { with: /\A\d{5}-\d{3}\z/ }
  validates :state, format: { with: /\A[A-Z]{2}\z/ }
  validates :code, length: { is: 3 }
  validates :postal_code, length: { is: 9 }
  validates :state, length: { is: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number,
                                                              :address, :city, :state, :postal_code, :email,
                                                              :phone_number))
    if @supplier.save
      flash[:success] = 'Fornecedor cadastrado com sucesso!'
      redirect_to @supplier
    else
      flash[:error] = 'Dados incompletos...'
      render 'new'
    end
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[show edit update destroy]

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_attributes)

    if @warehouse.save
      flash[:success] = 'Galpão cadastrado com sucesso!'
      redirect_to @warehouse
    else
      flash.now[:error] = 'Dados incompletos...'
      render 'new'
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_attributes)
      flash[:success] = 'Galpão atualizado com sucesso!'
      redirect_to @warehouse
    else
      flash.now[:error] = 'Não foi possível atualizar o galpão...'
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    flash[:success] = 'Galpão removido com sucesso!'
    redirect_to root_path
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_attributes
    params.require(:warehouse).permit(:name, :description, :code, :address,
                                      :city, :state, :postal_code, :area)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section id='warehouses'>
  <h2>Galpões</h2>
  <% if @warehouses.empty? %>
    <p>Não existem galpões cadastrados</p>
  <% else %>
    <% @warehouses.each do |warehouse| %>
      <div>
        <h3><%= link_to warehouse.name, warehouse %></h3>
        <dl>
          <dt><strong>Código:</strong></dt>
          <dd><%= warehouse.code %></dd>
          <dt><strong>Cidade:</strong></dt>
          <dd><%= warehouse.city %></dd>
          <dt><strong>Área:</strong></dt>
          <dd><%= warehouse.area %>m²</dd>
        </dl>
      </div>
    <% end %>
  <% end %>
  <div>
    <%= link_to 'Cadastrar Galpão', new_warehouse_path %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1>Galpões & Estoque</h1>
      <nav>
        <ul>
          <li><%= link_to 'Fornecedores', suppliers_path %></li>
        </ul>
      </nav>
    </header>
    <main>
      <div>
        <%= flash[:success] %>
      </div>
      <div>
        <%= flash[:error] %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.number_field :registration_number %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :phone_number %>
    <%= f.telephone_field :phone_number %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', suppliers_path %>

app/views/suppliers/index.html.erb
<h2>Fornecedores</h2>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= link_to supplier.brand_name, supplier %></td>
        <td><%= supplier.city %>/<%= supplier.state %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem fornecedores cadastrados</p>
<% end %>
<div>
  <%= link_to 'Cadastrar Fornecedor', new_supplier_path %>
</div>
<div>
  <%= link_to 'Voltar', root_path %>
</div>

app/views/suppliers/new.html.erb
<h2>Novo Fornecedor</h2>
<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'form' %>

app/views/suppliers/show.html.erb
<h2>Fornecedor <%= @supplier.brand_name %></h2>
<h3><%= @supplier.corporate_name %></h3>
<div>
  <dl>
    <dt><strong>CNPJ:</strong></dt>
    <dd><%= @supplier.registration_number %></dd>
    <dt><strong>Endereço:</strong></dt>
    <dd><%= @supplier.address %> - <%= @supplier.city %>/<%= @supplier.state %></dd>
    <dt><strong>CEP:</strong></dt>
    <dd><%= @supplier.postal_code %></dd>
    <dt><strong>Email:</strong></dt>
    <dd><%= @supplier.email %></dd>
    <dt><strong>Telefone:</strong></dt>
    <dd><%= @supplier.phone_number %></dd>
  </dl>
</div>
<div>
  <%= link_to 'Voltar', suppliers_path %>
</div>

app/views/warehouses/_form.html.erb
<%= form_with model: @warehouse do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
  </div>
  <div>
    <%= f.label :area %>
    <%= f.number_field :area %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/warehouses/edit.html.erb
<h2>Editar Galpão</h2>

<%= render 'form' %>

app/views/warehouses/new.html.erb
<h2>Novo Galpão</h2>
<% if @warehouse.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @warehouse.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'form' %>

app/views/warehouses/show.html.erb
<h2>Galpão <%= @warehouse.code %></h2>
<h3><%= @warehouse.description %></h3>
<div>
  <dl>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @warehouse.name %></dd>
    <dt><strong>Cidade:</strong></dt>
    <dd><%= @warehouse.city %>/<%= @warehouse.state %></dd>
    <dt><strong>Área:</strong></dt>
    <dd><%= @warehouse.area %>m²</dd>
    <dt><strong>Endereço:</strong></dt>
    <dd><%= @warehouse.address %> <strong>CEP: </strong><%= @warehouse.postal_code %></dd>
  </dl>
</div>

<div>
  <%= link_to 'Editar', edit_warehouse_path(@warehouse) %>
  <%= button_to 'Remover Galpão', @warehouse, method: :delete %>
</div>
<div>
  <%= link_to 'Voltar', root_path %>
</div>